/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TierBandSetPropertyInner1 } from './tier-band-set-property-inner1';

/**
 * Details about the interest that may be payable to the PCA account holders
 * @export
 * @interface CreditInterestProperty1
 */
export interface CreditInterestProperty1 {
    /**
     * The group of tiers or bands for which credit interest can be applied.
     * @type {Array<TierBandSetPropertyInner1>}
     * @memberof CreditInterestProperty1
     */
    'TierBandSet': Array<TierBandSetPropertyInner1>;
}

