/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeApplicableRangeProperty } from './fee-applicable-range-property';
import { FeeChargeCapPropertyInner } from './fee-charge-cap-property-inner';
import { OtherApplicationFrequencyProperty1 } from './other-application-frequency-property1';
import { OtherCalculationFrequencyProperty1 } from './other-calculation-frequency-property1';
import { OtherFeeCategoryTypeProperty } from './other-fee-category-type-property';
import { OtherFeeRateTypeProperty } from './other-fee-rate-type-property';
import { OtherFeeTypeProperty } from './other-fee-type-property';

/**
 * Other fees/charges details
 * @export
 * @interface FeeChargeDetailPropertyInner
 */
export interface FeeChargeDetailPropertyInner {
    /**
     * How frequently the fee/charge is applied to the account
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'ApplicationFrequency': FeeChargeDetailPropertyInnerApplicationFrequencyEnum;
    /**
     * How frequently the fee/charge is calculated
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'CalculationFrequency'?: FeeChargeDetailPropertyInnerCalculationFrequencyEnum;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeAmount'?: string;
    /**
     * 
     * @type {FeeApplicableRangeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeApplicableRange'?: FeeApplicableRangeProperty;
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeCategory': FeeChargeDetailPropertyInnerFeeCategoryEnum;
    /**
     * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
     * @type {Array<FeeChargeCapPropertyInner>}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner>;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeRateType'?: FeeChargeDetailPropertyInnerFeeRateTypeEnum;
    /**
     * Fee/Charge Type
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeType': FeeChargeDetailPropertyInnerFeeTypeEnum;
    /**
     * Fee/charge which is usually negotiable rather than a fixed amount
     * @type {boolean}
     * @memberof FeeChargeDetailPropertyInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Optional additional notes to supplement the fee/charge details.
     * @type {Array<string>}
     * @memberof FeeChargeDetailPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty1}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty1;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty1}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty1;
    /**
     * 
     * @type {OtherFeeCategoryTypeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeCategoryType'?: OtherFeeCategoryTypeProperty;
    /**
     * 
     * @type {OtherFeeRateTypeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty;
    /**
     * 
     * @type {OtherFeeTypeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeType'?: OtherFeeTypeProperty;
}

type FeeChargeDetailPropertyInnerApplicationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInnerCalculationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInnerFeeCategoryEnum = 'Other' | 'Servicing'
type FeeChargeDetailPropertyInnerFeeRateTypeEnum = 'Gross' | 'Other'
type FeeChargeDetailPropertyInnerFeeTypeEnum = 'Other' | 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCAccountFeeQuarterly' | 'ServiceCFixedTariff' | 'ServiceCBusiDepAccBreakage' | 'ServiceCMinimumMonthlyFee' | 'ServiceCOther'


