/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeApplicableRangeProperty } from './fee-applicable-range-property';
import { FeeChargeCapPropertyInner1 } from './fee-charge-cap-property-inner1';
import { OtherApplicationFrequencyProperty1 } from './other-application-frequency-property1';
import { OtherCalculationFrequencyProperty1 } from './other-calculation-frequency-property1';
import { OtherFeeCategoryTypeProperty } from './other-fee-category-type-property';
import { OtherFeeRateTypeProperty } from './other-fee-rate-type-property';
import { OtherFeeTypeProperty } from './other-fee-type-property';

/**
 * Other fees/charges details
 * @export
 * @interface FeeChargeDetailPropertyInner1
 */
export interface FeeChargeDetailPropertyInner1 {
    /**
     * How frequently the fee/charge is applied to the account
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'ApplicationFrequency': FeeChargeDetailPropertyInner1ApplicationFrequencyEnum;
    /**
     * How frequently the fee/charge is calculated
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'CalculationFrequency'?: FeeChargeDetailPropertyInner1CalculationFrequencyEnum;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeAmount'?: string;
    /**
     * 
     * @type {FeeApplicableRangeProperty}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeApplicableRange'?: FeeApplicableRangeProperty;
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeCategory': FeeChargeDetailPropertyInner1FeeCategoryEnum;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     * @type {Array<FeeChargeCapPropertyInner1>}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner1>;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeRateType'?: FeeChargeDetailPropertyInner1FeeRateTypeEnum;
    /**
     * Fee/Charge Type
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeType': FeeChargeDetailPropertyInner1FeeTypeEnum;
    /**
     * Optional additional notes to supplement the fee/charge details.
     * @type {Array<string>}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty1}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty1;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty1}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty1;
    /**
     * 
     * @type {OtherFeeCategoryTypeProperty}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeCategoryType'?: OtherFeeCategoryTypeProperty;
    /**
     * 
     * @type {OtherFeeRateTypeProperty}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty;
    /**
     * 
     * @type {OtherFeeTypeProperty}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeType'?: OtherFeeTypeProperty;
}

type FeeChargeDetailPropertyInner1ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInner1CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInner1FeeCategoryEnum = 'Other' | 'Servicing'
type FeeChargeDetailPropertyInner1FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'
type FeeChargeDetailPropertyInner1FeeTypeEnum = 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCOther' | 'Other'


