/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherFeeTypePropertyInner } from './other-fee-type-property-inner';

/**
 * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
 * @export
 * @interface FeeChargeCapPropertyInner
 */
export interface FeeChargeCapPropertyInner {
    /**
     * Period e.g. day, week, month etc. for which the fee/charge is capped
     * @type {string}
     * @memberof FeeChargeCapPropertyInner
     */
    'CappingPeriod'?: FeeChargeCapPropertyInnerCappingPeriodEnum;
    /**
     * Cap amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof FeeChargeCapPropertyInner
     */
    'FeeCapAmount'?: string;
    /**
     * fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount
     * @type {number}
     * @memberof FeeChargeCapPropertyInner
     */
    'FeeCapOccurrence'?: number;
    /**
     * Fee/charge type which is being capped
     * @type {Array<string>}
     * @memberof FeeChargeCapPropertyInner
     */
    'FeeType': Array<FeeChargeCapPropertyInnerFeeTypeEnum>;
    /**
     * Min Max type
     * @type {string}
     * @memberof FeeChargeCapPropertyInner
     */
    'MinMaxType': FeeChargeCapPropertyInnerMinMaxTypeEnum;
    /**
     * Free text for adding  extra details for fee charge cap
     * @type {Array<string>}
     * @memberof FeeChargeCapPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Other fee type code which is not available in the standard code set
     * @type {Array<OtherFeeTypePropertyInner>}
     * @memberof FeeChargeCapPropertyInner
     */
    'OtherFeeType'?: Array<OtherFeeTypePropertyInner>;
}

type FeeChargeCapPropertyInnerCappingPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year'
type FeeChargeCapPropertyInnerFeeTypeEnum = 'Other' | 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCAccountFeeQuarterly' | 'ServiceCFixedTariff' | 'ServiceCBusiDepAccBreakage' | 'ServiceCMinimumMonthlyFee' | 'ServiceCOther'
type FeeChargeCapPropertyInnerMinMaxTypeEnum = 'Minimum' | 'Maximum'


