/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Links relevant to the payload
 * @export
 * @interface Links
 */
export interface Links {
    /**
     * 
     * @type {string}
     * @memberof Links
     */
    'First'?: string;
    /**
     * 
     * @type {string}
     * @memberof Links
     */
    'Last'?: string;
    /**
     * 
     * @type {string}
     * @memberof Links
     */
    'Next'?: string;
    /**
     * 
     * @type {string}
     * @memberof Links
     */
    'Prev'?: string;
    /**
     * 
     * @type {string}
     * @memberof Links
     */
    'Self': string;
}

