/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Meta Data relevant to the payload
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof Meta
     */
    'FirstAvailableDateTime'?: string;
    /**
     * All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof Meta
     */
    'LastAvailableDateTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    'TotalPages'?: number;
}

