/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Amount of money associated with the statement interest amount type.
 * @export
 * @interface OBActiveOrHistoricCurrencyAndAmount7
 */
export interface OBActiveOrHistoricCurrencyAndAmount7 {
    /**
     * A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217.
     * @type {string}
     * @memberof OBActiveOrHistoricCurrencyAndAmount7
     */
    'Amount': string;
    /**
     * A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\".
     * @type {string}
     * @memberof OBActiveOrHistoricCurrencyAndAmount7
     */
    'Currency': string;
}

