/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Set of elements used to fully identify the type of underlying transaction resulting in an entry.
 * @export
 * @interface OBBankTransactionCodeStructure1
 */
export interface OBBankTransactionCodeStructure1 {
    /**
     * Specifies the family within a domain.
     * @type {string}
     * @memberof OBBankTransactionCodeStructure1
     */
    'Code': string;
    /**
     * Specifies the sub-product family within a specific family.
     * @type {string}
     * @memberof OBBankTransactionCodeStructure1
     */
    'SubCode': string;
}

