/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Balance type, in a coded form.
 * @export
 * @enum {string}
 */
export type OBBalanceType1Code = 'ClosingAvailable' | 'ClosingBooked' | 'ClosingCleared' | 'Expected' | 'ForwardAvailable' | 'Information' | 'InterimAvailable' | 'InterimBooked' | 'InterimCleared' | 'OpeningAvailable' | 'OpeningBooked' | 'OpeningCleared' | 'PreviouslyClosedBooked'

