/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreditInterestProperty } from './credit-interest-property';
import { OtherFeesChargesPropertyInner } from './other-fees-charges-property-inner';
import { OverdraftProperty } from './overdraft-property';
import { ProductDetailsProperty } from './product-details-property';

/**
 * 
 * @export
 * @interface OBBCAData1
 */
export interface OBBCAData1 {
    /**
     * 
     * @type {CreditInterestProperty}
     * @memberof OBBCAData1
     */
    'CreditInterest'?: CreditInterestProperty;
    /**
     * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
     * @type {Array<OtherFeesChargesPropertyInner>}
     * @memberof OBBCAData1
     */
    'OtherFeesCharges'?: Array<OtherFeesChargesPropertyInner>;
    /**
     * 
     * @type {OverdraftProperty}
     * @memberof OBBCAData1
     */
    'Overdraft'?: OverdraftProperty;
    /**
     * 
     * @type {ProductDetailsProperty}
     * @memberof OBBCAData1
     */
    'ProductDetails'?: ProductDetailsProperty;
}

