/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Provides the details to identify the beneficiary account.
 * @export
 * @interface OBCashAccount51
 */
export interface OBCashAccount51 {
    /**
     * Beneficiary account identification.
     * @type {string}
     * @memberof OBCashAccount51
     */
    'Identification': string;
    /**
     * The account name is the name or names of the account owner(s) represented at an account level, as displayed by the ASPSP\'s online channels. Note, the account name is not the product name or the nickname of the account.
     * @type {string}
     * @memberof OBCashAccount51
     */
    'Name'?: string;
    /**
     * Name of the identification scheme, in a coded form as published in an external list.
     * @type {string}
     * @memberof OBCashAccount51
     */
    'SchemeName': string;
    /**
     * This is secondary identification of the account, as assigned by the account servicing institution.  This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination).
     * @type {string}
     * @memberof OBCashAccount51
     */
    'SecondaryIdentification'?: string;
}

