/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBCurrencyExchange5InstructedAmount } from './obcurrency-exchange5-instructed-amount';

/**
 * Set of elements used to provide details on the currency exchange.
 * @export
 * @interface OBCurrencyExchange5
 */
export interface OBCurrencyExchange5 {
    /**
     * Unique identification to unambiguously identify the foreign exchange contract.
     * @type {string}
     * @memberof OBCurrencyExchange5
     */
    'ContractIdentification'?: string;
    /**
     * Factor used to convert an amount from one currency into another. This reflects the price at which one currency was bought with another currency. Usage: ExchangeRate expresses the ratio between UnitCurrency and QuotedCurrency (ExchangeRate = UnitCurrency/QuotedCurrency).
     * @type {number}
     * @memberof OBCurrencyExchange5
     */
    'ExchangeRate': number;
    /**
     * 
     * @type {OBCurrencyExchange5InstructedAmount}
     * @memberof OBCurrencyExchange5
     */
    'InstructedAmount'?: OBCurrencyExchange5InstructedAmount;
    /**
     * Date and time at which an exchange rate is quoted.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBCurrencyExchange5
     */
    'QuotationDate'?: string;
    /**
     * Currency from which an amount is to be converted in a currency conversion.
     * @type {string}
     * @memberof OBCurrencyExchange5
     */
    'SourceCurrency': string;
    /**
     * Currency into which an amount is to be converted in a currency conversion.
     * @type {string}
     * @memberof OBCurrencyExchange5
     */
    'TargetCurrency'?: string;
    /**
     * Currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is GBP.
     * @type {string}
     * @memberof OBCurrencyExchange5
     */
    'UnitCurrency'?: string;
}

