/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Status of a transaction entry on the books of the account servicer.
 * @export
 * @enum {string}
 */
export type OBEntryStatus1Code = 'Booked' | 'Pending'

