/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OBError1
 */
export interface OBError1 {
    /**
     * Low level textual error code, e.g., UK.OBIE.Field.Missing
     * @type {string}
     * @memberof OBError1
     */
    'ErrorCode': string;
    /**
     * A description of the error that occurred. e.g., \'A mandatory field isn\'t supplied\' or \'RequestedExecutionDateTime must be in future\' OBIE doesn\'t standardise this field
     * @type {string}
     * @memberof OBError1
     */
    'Message': string;
    /**
     * Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency
     * @type {string}
     * @memberof OBError1
     */
    'Path'?: string;
    /**
     * URL to help remediate the problem, or provide more information, or to API Reference, or help etc
     * @type {string}
     * @memberof OBError1
     */
    'Url'?: string;
}

