/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBError1 } from './oberror1';

/**
 * An array of detail error codes, and messages, and URLs to documentation to help remediation.
 * @export
 * @interface OBErrorResponse1
 */
export interface OBErrorResponse1 {
    /**
     * High level textual error code, to help categorize the errors.
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Code': string;
    /**
     * 
     * @type {Array<OBError1>}
     * @memberof OBErrorResponse1
     */
    'Errors': Array<OBError1>;
    /**
     * A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Id'?: string;
    /**
     * Brief Error message, e.g., \'There is something wrong with the request parameters provided\'
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Message': string;
}

