/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the scheduled payment date type requested
 * @export
 * @enum {string}
 */
export type OBExternalScheduleType1Code = 'Arrival' | 'Execution'

