/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Party type, in a coded form.
 * @export
 * @enum {string}
 */
export type OBExternalPartyType1Code = 'Delegate' | 'Joint' | 'Sole'

