/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Specifies the status of the direct debit in code form.
 * @export
 * @enum {string}
 */
export type OBExternalDirectDebitStatus1Code = 'Active' | 'Inactive'

