/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * How frequently the fee/charge is applied to the account
 * @export
 * @enum {string}
 */
export type OBFeeFrequency1Code2 = 'FEAC' | 'FEAO' | 'FECP' | 'FEDA' | 'FEHO' | 'FEI' | 'FEMO' | 'FEOA' | 'FEOT' | 'FEPC' | 'FEPH' | 'FEPO' | 'FEPS' | 'FEPT' | 'FEPTA' | 'FEPTP' | 'FEQU' | 'FESM' | 'FEST' | 'FEWE' | 'FEYE'

