/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
 * @export
 * @enum {string}
 */
export type OBInterestRateType1Code0 = 'INBB' | 'INFR' | 'INGR' | 'INLR' | 'INNE' | 'INOT'

