/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details of the merchant involved in the transaction.
 * @export
 * @interface OBMerchantDetails1
 */
export interface OBMerchantDetails1 {
    /**
     * Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
     * @type {string}
     * @memberof OBMerchantDetails1
     */
    'MerchantCategoryCode'?: string;
    /**
     * Name by which the merchant is known.
     * @type {string}
     * @memberof OBMerchantDetails1
     */
    'MerchantName'?: string;
}

