/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAddressTypeCode } from './obaddress-type-code';

/**
 * Postal address of a party.
 * @export
 * @interface OBParty2AddressInner
 */
export interface OBParty2AddressInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof OBParty2AddressInner
     */
    'AddressLine'?: Array<string>;
    /**
     * Identifies the nature of the postal address.
     * @type {OBAddressTypeCode}
     * @memberof OBParty2AddressInner
     */
    'AddressType'?: OBAddressTypeCode;
    /**
     * Number that identifies the position of a building on a street.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'BuildingNumber'?: string;
    /**
     * Nation with its own government, occupying a particular territory.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'Country': string;
    /**
     * Identifies a subdivision of a country eg, state, region, county.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'CountrySubDivision'?: string;
    /**
     * Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'PostCode'?: string;
    /**
     * Name of a street or thoroughfare.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'StreetName'?: string;
    /**
     * Name of a built-up area, with defined boundaries, and a local government.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'TownName'?: string;
}

