/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Relationship to the Account resource.
 * @export
 * @interface OBPartyRelationships1Account
 */
export interface OBPartyRelationships1Account {
    /**
     * Unique identification as assigned by the ASPSP to uniquely identify the related resource.
     * @type {string}
     * @memberof OBPartyRelationships1Account
     */
    'Id': string;
    /**
     * Absolute URI to the related resource.
     * @type {string}
     * @memberof OBPartyRelationships1Account
     */
    'Related': string;
}

