/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreditInterestProperty1 } from './credit-interest-property1';
import { OtherFeesChargesProperty } from './other-fees-charges-property';
import { OverdraftProperty1 } from './overdraft-property1';
import { ProductDetailsProperty1 } from './product-details-property1';

/**
 * 
 * @export
 * @interface OBPCAData1
 */
export interface OBPCAData1 {
    /**
     * 
     * @type {CreditInterestProperty1}
     * @memberof OBPCAData1
     */
    'CreditInterest'?: CreditInterestProperty1;
    /**
     * 
     * @type {OtherFeesChargesProperty}
     * @memberof OBPCAData1
     */
    'OtherFeesCharges'?: OtherFeesChargesProperty;
    /**
     * 
     * @type {OverdraftProperty1}
     * @memberof OBPCAData1
     */
    'Overdraft'?: OverdraftProperty1;
    /**
     * 
     * @type {ProductDetailsProperty1}
     * @memberof OBPCAData1
     */
    'ProductDetails'?: ProductDetailsProperty1;
}

