/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAddressTypeCode } from './obaddress-type-code';

/**
 * Information that locates and identifies a specific address, as defined by postal services.
 * @export
 * @interface OBPostalAddress6
 */
export interface OBPostalAddress6 {
    /**
     * 
     * @type {Array<string>}
     * @memberof OBPostalAddress6
     */
    'AddressLine'?: Array<string>;
    /**
     * Identifies the nature of the postal address.
     * @type {OBAddressTypeCode}
     * @memberof OBPostalAddress6
     */
    'AddressType'?: OBAddressTypeCode;
    /**
     * Number that identifies the position of a building on a street.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'BuildingNumber'?: string;
    /**
     * Nation with its own government.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'Country'?: string;
    /**
     * Identifies a subdivision of a country such as state, region, county.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'CountrySubDivision'?: string;
    /**
     * Identification of a division of a large organisation or building.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'Department'?: string;
    /**
     * Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'PostCode'?: string;
    /**
     * Name of a street or thoroughfare.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'StreetName'?: string;
    /**
     * Identification of a sub-division of a large organisation or building.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'SubDepartment'?: string;
    /**
     * Name of a built-up area, with defined boundaries, and a local government.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'TownName'?: string;
}

