/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBInterestCalculationMethod1Code } from './obinterest-calculation-method1-code';
import { OBOtherCodeType10 } from './obother-code-type10';
import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner } from './obread-product2-data-product-inner-other-product-type-credit-interest-tier-band-set-inner-tier-band-inner';

/**
 * The group of tiers or bands for which credit interest can be applied.
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner {
    /**
     * Methods of calculating interest
     * @type {OBInterestCalculationMethod1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'CalculationMethod'?: OBInterestCalculationMethod1Code;
    /**
     * Describes whether accrued interest is payable only to the BCA or to another bank account
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'Destination': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerDestinationEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'OtherCalculationMethod'?: OBOtherCodeType10;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'OtherDestination'?: OBOtherCodeType10;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'TierBand': Array<OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner>;
    /**
     * The methodology of how credit interest is paid/applied. It can be:- 1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases. 2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance. 3. Whole The same interest rate is applied irrespective of the product holder\'s account balance
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'TierBandMethod': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandMethodEnum;
}

type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerDestinationEnum = 'INOT' | 'INPA' | 'INSC'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandMethodEnum = 'INBA' | 'INTI' | 'INWH'


