/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBBeneficiary5 } from './obbeneficiary5';

/**
 * 
 * @export
 * @interface OBReadBeneficiary5Data
 */
export interface OBReadBeneficiary5Data {
    /**
     * 
     * @type {Array<OBBeneficiary5>}
     * @memberof OBReadBeneficiary5Data
     */
    'Beneficiary'?: Array<OBBeneficiary5>;
}

