/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterest } from './obread-product2-data-product-inner-other-product-type-credit-interest';
import { OBReadProduct2DataProductInnerOtherProductTypeLoanInterest } from './obread-product2-data-product-inner-other-product-type-loan-interest';
import { OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner } from './obread-product2-data-product-inner-other-product-type-other-fees-charges-inner';
import { OBReadProduct2DataProductInnerOtherProductTypeOverdraft } from './obread-product2-data-product-inner-other-product-type-overdraft';
import { OBReadProduct2DataProductInnerOtherProductTypeProductDetails } from './obread-product2-data-product-inner-other-product-type-product-details';
import { OBReadProduct2DataProductInnerOtherProductTypeRepayment } from './obread-product2-data-product-inner-other-product-type-repayment';

/**
 * Other product type details associated with the account.
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductType
 */
export interface OBReadProduct2DataProductInnerOtherProductType {
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeCreditInterest}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'CreditInterest'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterest;
    /**
     * Description of the Product associated with the account
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Description': string;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeLoanInterest}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'LoanInterest'?: OBReadProduct2DataProductInnerOtherProductTypeLoanInterest;
    /**
     * Long name associated with the product
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Name': string;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'OtherFeesCharges'?: Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner>;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeOverdraft}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Overdraft'?: OBReadProduct2DataProductInnerOtherProductTypeOverdraft;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeProductDetails}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'ProductDetails'?: OBReadProduct2DataProductInnerOtherProductTypeProductDetails;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepayment}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Repayment'?: OBReadProduct2DataProductInnerOtherProductTypeRepayment;
    /**
     * Additional information that can not be captured in the structured fields and/or any other specific block.
     * @type {{ [key: string]: any; }}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'SupplementaryData'?: { [key: string]: any; };
}

