/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInner } from './obread-product2-data-product-inner-other-product-type-overdraft-overdraft-tier-band-set-inner';

/**
 * Borrowing details
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeOverdraft
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeOverdraft {
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraft
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraft
     */
    'OverdraftTierBandSet': Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInner>;
}

