/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadOffer1Data } from './obread-offer1-data';

/**
 * 
 * @export
 * @interface OBReadOffer1
 */
export interface OBReadOffer1 {
    /**
     * 
     * @type {OBReadOffer1Data}
     * @memberof OBReadOffer1
     */
    'Data': OBReadOffer1Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadOffer1
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadOffer1
     */
    'Meta'?: Meta;
}

