/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadBalance1Data } from './obread-balance1-data';

/**
 * 
 * @export
 * @interface OBReadBalance1
 */
export interface OBReadBalance1 {
    /**
     * 
     * @type {OBReadBalance1Data}
     * @memberof OBReadBalance1
     */
    'Data': OBReadBalance1Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadBalance1
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadBalance1
     */
    'Meta'?: Meta;
}

