/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadAccount6Data } from './obread-account6-data';

/**
 * 
 * @export
 * @interface OBReadAccount6
 */
export interface OBReadAccount6 {
    /**
     * 
     * @type {OBReadAccount6Data}
     * @memberof OBReadAccount6
     */
    'Data': OBReadAccount6Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadAccount6
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadAccount6
     */
    'Meta'?: Meta;
}

