/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBStatement2 } from './obstatement2';

/**
 * 
 * @export
 * @interface OBReadDataStatement2
 */
export interface OBReadDataStatement2 {
    /**
     * 
     * @type {Array<OBStatement2>}
     * @memberof OBReadDataStatement2
     */
    'Statement'?: Array<OBStatement2>;
}

