/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadOffer1DataOfferInnerAmount } from './obread-offer1-data-offer-inner-amount';
import { OBReadOffer1DataOfferInnerFee } from './obread-offer1-data-offer-inner-fee';

/**
 * 
 * @export
 * @interface OBReadOffer1DataOfferInner
 */
export interface OBReadOffer1DataOfferInner {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'AccountId': string;
    /**
     * 
     * @type {OBReadOffer1DataOfferInnerAmount}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Amount'?: OBReadOffer1DataOfferInnerAmount;
    /**
     * Further details of the offer.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Description'?: string;
    /**
     * Date and time at which the offer ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'EndDateTime'?: string;
    /**
     * 
     * @type {OBReadOffer1DataOfferInnerFee}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Fee'?: OBReadOffer1DataOfferInnerFee;
    /**
     * A unique and immutable identifier used to identify the offer resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'OfferId'?: string;
    /**
     * Offer type, in a coded form.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'OfferType'?: OBReadOffer1DataOfferInnerOfferTypeEnum;
    /**
     * Rate associated with the offer type.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Rate'?: string;
    /**
     * Date and time at which the offer starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'StartDateTime'?: string;
    /**
     * Further details of the term of the offer.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Term'?: string;
    /**
     * URL (Uniform Resource Locator) where documentation on the offer can be found
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'URL'?: string;
    /**
     * Value associated with the offer type.
     * @type {number}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Value'?: number;
}

type OBReadOffer1DataOfferInnerOfferTypeEnum = 'BalanceTransfer' | 'LimitIncrease' | 'MoneyTransfer' | 'Other' | 'PromotionalRate'


