/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount0 } from './obactive-or-historic-currency-and-amount0';
import { OBExternalDirectDebitStatus1Code } from './obexternal-direct-debit-status1-code';

/**
 * Account to or from which a cash entry is made.
 * @export
 * @interface OBReadDirectDebit2DataDirectDebitInner
 */
export interface OBReadDirectDebit2DataDirectDebitInner {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'AccountId': string;
    /**
     * A unique and immutable identifier used to identify the direct debit resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'DirectDebitId'?: string;
    /**
     * Specifies the status of the direct debit in code form.
     * @type {OBExternalDirectDebitStatus1Code}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'DirectDebitStatusCode'?: OBExternalDirectDebitStatus1Code;
    /**
     * Regularity with which direct debit instructions are to be created and processed.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'Frequency'?: string;
    /**
     * Direct Debit reference. For AUDDIS service users provide Core Reference. For non AUDDIS service users provide Core reference if possible or last used reference.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'MandateIdentification': string;
    /**
     * Name of Service User.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'Name': string;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount0}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'PreviousPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount0;
    /**
     * Date of most recent direct debit collection.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'PreviousPaymentDateTime'?: string;
}

