/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherAmountType } from './obread-product2-data-product-inner-other-product-type-repayment-other-amount-type';
import { OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentFrequency } from './obread-product2-data-product-inner-other-product-type-repayment-other-repayment-frequency';
import { OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentType } from './obread-product2-data-product-inner-other-product-type-repayment-other-repayment-type';
import { OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeCharges } from './obread-product2-data-product-inner-other-product-type-repayment-repayment-fee-charges';
import { OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner } from './obread-product2-data-product-inner-other-product-type-repayment-repayment-holiday-inner';

/**
 * Repayment details of the Loan product
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeRepayment
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeRepayment {
    /**
     * The repayment is for paying just the interest only or both interest and capital or bullet amount or balance to date etc
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'AmountType'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentAmountTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherAmountType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'OtherAmountType'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherAmountType;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentFrequency}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'OtherRepaymentFrequency'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentFrequency;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'OtherRepaymentType'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentOtherRepaymentType;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeCharges}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'RepaymentFeeCharges'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeCharges;
    /**
     * Repayment frequency
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'RepaymentFrequency'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFrequencyEnum;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'RepaymentHoliday'?: Array<OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner>;
    /**
     * Repayment type
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepayment
     */
    'RepaymentType'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentTypeEnum;
}

type OBReadProduct2DataProductInnerOtherProductTypeRepaymentAmountTypeEnum = 'RABD' | 'RABL' | 'RACI' | 'RAFC' | 'RAIO' | 'RALT' | 'USOT'
type OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFrequencyEnum = 'SMDA' | 'SMFL' | 'SMFO' | 'SMHY' | 'SMMO' | 'SMOT' | 'SMQU' | 'SMWE' | 'SMYE'
type OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentTypeEnum = 'USBA' | 'USBU' | 'USCI' | 'USCS' | 'USER' | 'USFA' | 'USFB' | 'USFI' | 'USIO' | 'USOT' | 'USPF' | 'USRW' | 'USSL'


