/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadOffer1DataOfferInner } from './obread-offer1-data-offer-inner';

/**
 * 
 * @export
 * @interface OBReadOffer1Data
 */
export interface OBReadOffer1Data {
    /**
     * 
     * @type {Array<OBReadOffer1DataOfferInner>}
     * @memberof OBReadOffer1Data
     */
    'Offer'?: Array<OBReadOffer1DataOfferInner>;
}

