/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadParty3Data } from './obread-party3-data';

/**
 * 
 * @export
 * @interface OBReadParty3
 */
export interface OBReadParty3 {
    /**
     * 
     * @type {OBReadParty3Data}
     * @memberof OBReadParty3
     */
    'Data': OBReadParty3Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadParty3
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadParty3
     */
    'Meta'?: Meta;
}

