/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner } from './obread-product2-data-product-inner-other-product-type-loan-interest-loan-interest-tier-band-set-inner';

/**
 * Details about the interest that may be payable to the SME Loan holders
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeLoanInterest
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeLoanInterest {
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeLoanInterest
     */
    'LoanInterestTierBandSet': Array<OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeLoanInterest
     */
    'Notes'?: Array<string>;
}

