/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBOtherCodeType10 } from './obother-code-type10';

/**
 * 
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeProductDetails
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeProductDetails {
    /**
     * The length/duration of the fee free period
     * @type {number}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'FeeFreeLength'?: number;
    /**
     * The unit of period (days, weeks, months etc.) of the promotional length
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'FeeFreeLengthPeriod'?: OBReadProduct2DataProductInnerOtherProductTypeProductDetailsFeeFreeLengthPeriodEnum;
    /**
     * The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'MonthlyMaximumCharge'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'OtherSegment'?: OBOtherCodeType10;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    'Segment'?: Array<OBReadProduct2DataProductInnerOtherProductTypeProductDetailsSegmentEnum>;
}

type OBReadProduct2DataProductInnerOtherProductTypeProductDetailsFeeFreeLengthPeriodEnum = 'PACT' | 'PDAY' | 'PHYR' | 'PMTH' | 'PQTR' | 'PWEK' | 'PYER'
type OBReadProduct2DataProductInnerOtherProductTypeProductDetailsSegmentEnum = 'GEAS' | 'GEBA' | 'GEBR' | 'GEBU' | 'GECI' | 'GECS' | 'GEFB' | 'GEFG' | 'GEG' | 'GEGR' | 'GEGS' | 'GEOT' | 'GEOV' | 'GEPA' | 'GEPR' | 'GERE' | 'GEST' | 'GEYA' | 'GEYO' | 'PSCA' | 'PSES' | 'PSNC' | 'PSNP' | 'PSRG' | 'PSSS' | 'PSST' | 'PSSW'


