/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBStandingOrder6 } from './obstanding-order6';

/**
 * 
 * @export
 * @interface OBReadStandingOrder6Data
 */
export interface OBReadStandingOrder6Data {
    /**
     * 
     * @type {Array<OBStandingOrder6>}
     * @memberof OBReadStandingOrder6Data
     */
    'StandingOrder'?: Array<OBStandingOrder6>;
}

