/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadScheduledPayment3Data } from './obread-scheduled-payment3-data';

/**
 * 
 * @export
 * @interface OBReadScheduledPayment3
 */
export interface OBReadScheduledPayment3 {
    /**
     * 
     * @type {OBReadScheduledPayment3Data}
     * @memberof OBReadScheduledPayment3
     */
    'Data': OBReadScheduledPayment3Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadScheduledPayment3
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadScheduledPayment3
     */
    'Meta'?: Meta;
}

