/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBFeeFrequency1Code0 } from './obfee-frequency1-code0';
import { OBFeeFrequency1Code1 } from './obfee-frequency1-code1';
import { OBInterestRateType1Code0 } from './obinterest-rate-type1-code0';
import { OBOtherCodeType11 } from './obother-code-type11';
import { OBOtherCodeType12 } from './obother-code-type12';
import { OBOtherCodeType13 } from './obother-code-type13';
import { OBOtherCodeType14 } from './obother-code-type14';
import { OBOverdraftFeeType1Code } from './oboverdraft-fee-type1-code';
import { OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner } from './obread-product2-data-product-inner-other-product-type-overdraft-overdraft-tier-band-set-inner-overdraft-fees-charges-inner-overdraft-fee-charge-cap-inner';

/**
 * Details about the fees/charges
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner {
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {OBFeeFrequency1Code0}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'ApplicationFrequency': OBFeeFrequency1Code0;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {OBFeeFrequency1Code1}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'CalculationFrequency'?: OBFeeFrequency1Code1;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {OBInterestRateType1Code0}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeRateType'?: OBInterestRateType1Code0;
    /**
     * Overdraft fee type
     * @type {OBOverdraftFeeType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeType': OBOverdraftFeeType1Code;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Indicates whether fee and charges are negotiable
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherCodeType11}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType11;
    /**
     * 
     * @type {OBOtherCodeType12}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType12;
    /**
     * 
     * @type {OBOtherCodeType14}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherFeeRateType'?: OBOtherCodeType14;
    /**
     * 
     * @type {OBOtherCodeType13}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherFeeType'?: OBOtherCodeType13;
    /**
     * Indicates if the fee/charge is already covered by an \'Overdraft Control\' fee or not.
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OverdraftFeeChargeCap'?: Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner>;
}

