/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBTransaction6 } from './obtransaction6';

/**
 * 
 * @export
 * @interface OBReadDataTransaction6
 */
export interface OBReadDataTransaction6 {
    /**
     * 
     * @type {Array<OBTransaction6>}
     * @memberof OBReadDataTransaction6
     */
    'Transaction'?: Array<OBTransaction6>;
}

