/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadBalance1DataBalanceInner } from './obread-balance1-data-balance-inner';

/**
 * 
 * @export
 * @interface OBReadBalance1Data
 */
export interface OBReadBalance1Data {
    /**
     * 
     * @type {Array<OBReadBalance1DataBalanceInner>}
     * @memberof OBReadBalance1Data
     */
    'Balance': Array<OBReadBalance1DataBalanceInner>;
}

