/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadParty2Data } from './obread-party2-data';

/**
 * 
 * @export
 * @interface OBReadParty2
 */
export interface OBReadParty2 {
    /**
     * 
     * @type {OBReadParty2Data}
     * @memberof OBReadParty2
     */
    'Data': OBReadParty2Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadParty2
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadParty2
     */
    'Meta'?: Meta;
}

