/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadProduct2Data } from './obread-product2-data';

/**
 * Product details of Other Product which is not avaiable in the standard list
 * @export
 * @interface OBReadProduct2
 */
export interface OBReadProduct2 {
    /**
     * 
     * @type {OBReadProduct2Data}
     * @memberof OBReadProduct2
     */
    'Data': OBReadProduct2Data;
    /**
     * 
     * @type {Links}
     * @memberof OBReadProduct2
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadProduct2
     */
    'Meta'?: Meta;
}

