/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { OBReadDataTransaction6 } from './obread-data-transaction6';

/**
 * 
 * @export
 * @interface OBReadTransaction6
 */
export interface OBReadTransaction6 {
    /**
     * 
     * @type {OBReadDataTransaction6}
     * @memberof OBReadTransaction6
     */
    'Data': OBReadDataTransaction6;
    /**
     * 
     * @type {Links}
     * @memberof OBReadTransaction6
     */
    'Links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof OBReadTransaction6
     */
    'Meta'?: Meta;
}

