/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBParty2 } from './obparty2';

/**
 * 
 * @export
 * @interface OBReadParty2Data
 */
export interface OBReadParty2Data {
    /**
     * 
     * @type {OBParty2}
     * @memberof OBReadParty2Data
     */
    'Party'?: OBParty2;
}

