/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OBReadConsentResponse1Data
 */
export interface OBReadConsentResponse1Data {
    /**
     * Unique identification as assigned to identify the account access consent resource.
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'ConsentId': string;
    /**
     * Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'CreationDateTime': string;
    /**
     * Specified date and time the permissions will expire. If this is not populated, the permissions will be open ended.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'ExpirationDateTime'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadConsentResponse1Data
     */
    'Permissions': Array<OBReadConsentResponse1DataPermissionsEnum>;
    /**
     * Specifies the status of consent resource in code form.
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'Status': OBReadConsentResponse1DataStatusEnum;
    /**
     * Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'StatusUpdateDateTime': string;
    /**
     * Specified start date and time for the transaction query period. If this is not populated, the start date will be open ended, and data will be returned from the earliest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'TransactionFromDateTime'?: string;
    /**
     * Specified end date and time for the transaction query period. If this is not populated, the end date will be open ended, and data will be returned to the latest available transaction.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadConsentResponse1Data
     */
    'TransactionToDateTime'?: string;
}

type OBReadConsentResponse1DataPermissionsEnum = 'ReadAccountsBasic' | 'ReadAccountsDetail' | 'ReadBalances' | 'ReadBeneficiariesBasic' | 'ReadBeneficiariesDetail' | 'ReadDirectDebits' | 'ReadOffers' | 'ReadPAN' | 'ReadParty' | 'ReadPartyPSU' | 'ReadProducts' | 'ReadScheduledPaymentsBasic' | 'ReadScheduledPaymentsDetail' | 'ReadStandingOrdersBasic' | 'ReadStandingOrdersDetail' | 'ReadStatementsBasic' | 'ReadStatementsDetail' | 'ReadTransactionsBasic' | 'ReadTransactionsCredits' | 'ReadTransactionsDebits' | 'ReadTransactionsDetail'
type OBReadConsentResponse1DataStatusEnum = 'Authorised' | 'AwaitingAuthorisation' | 'Rejected' | 'Revoked'


