/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadBalance1DataBalanceInnerCreditLineInnerAmount } from './obread-balance1-data-balance-inner-credit-line-inner-amount';

/**
 * Set of elements used to provide details on the credit line.
 * @export
 * @interface OBReadBalance1DataBalanceInnerCreditLineInner
 */
export interface OBReadBalance1DataBalanceInnerCreditLineInner {
    /**
     * 
     * @type {OBReadBalance1DataBalanceInnerCreditLineInnerAmount}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Amount'?: OBReadBalance1DataBalanceInnerCreditLineInnerAmount;
    /**
     * Indicates whether or not the credit line is included in the balance of the account. Usage: If not present, credit line is not included in the balance amount of the account.
     * @type {boolean}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Included': boolean;
    /**
     * Limit type, in a coded form.
     * @type {string}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Type'?: OBReadBalance1DataBalanceInnerCreditLineInnerTypeEnum;
}

type OBReadBalance1DataBalanceInnerCreditLineInnerTypeEnum = 'Available' | 'Credit' | 'Emergency' | 'Pre-Agreed' | 'Temporary'


