/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAccount6 } from './obaccount6';

/**
 * 
 * @export
 * @interface OBReadAccount6Data
 */
export interface OBReadAccount6Data {
    /**
     * 
     * @type {Array<OBAccount6>}
     * @memberof OBReadAccount6Data
     */
    'Account'?: Array<OBAccount6>;
}

