/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBScheduledPayment3 } from './obscheduled-payment3';

/**
 * 
 * @export
 * @interface OBReadScheduledPayment3Data
 */
export interface OBReadScheduledPayment3Data {
    /**
     * 
     * @type {Array<OBScheduledPayment3>}
     * @memberof OBReadScheduledPayment3Data
     */
    'ScheduledPayment'?: Array<OBScheduledPayment3>;
}

