/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInner } from './obread-product2-data-product-inner';

/**
 * Aligning with the read write specs structure.
 * @export
 * @interface OBReadProduct2Data
 */
export interface OBReadProduct2Data {
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInner>}
     * @memberof OBReadProduct2Data
     */
    'Product'?: Array<OBReadProduct2DataProductInner>;
}

