/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBInterestFixedVariableType1Code } from './obinterest-fixed-variable-type1-code';
import { OBOtherCodeType11 } from './obother-code-type11';
import { OBOtherCodeType12 } from './obother-code-type12';
import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType } from './obread-product2-data-product-inner-other-product-type-credit-interest-tier-band-set-inner-tier-band-inner-other-bank-interest-type';

/**
 * Tier Band Details
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner {
    /**
     * The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.  Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'AER': string;
    /**
     * How often is interest applied to the Product for this tier/band i.e. how often the financial institution pays accumulated interest to the customer\'s account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'ApplicationFrequency': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerApplicationFrequencyEnum;
    /**
     * Bank Interest for the product
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'BankInterestRate'?: string;
    /**
     * Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the account holder\'s account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'BankInterestRateType'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerBankInterestRateTypeEnum;
    /**
     * How often is credit interest calculated for the account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'CalculationFrequency'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerCalculationFrequencyEnum;
    /**
     * Amount on which Interest applied.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'DepositInterestAppliedCoverage'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerDepositInterestAppliedCoverageEnum;
    /**
     * Type of interest rate, Fixed or Variable
     * @type {OBInterestFixedVariableType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'FixedVariableInterestRateType': OBInterestFixedVariableType1Code;
    /**
     * Unique and unambiguous identification of a  Tier Band for the Product.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'Identification'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherCodeType11}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType11;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherBankInterestType'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType;
    /**
     * 
     * @type {OBOtherCodeType12}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType12;
    /**
     * Maximum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'TierValueMaximum'?: string;
    /**
     * Minimum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'TierValueMinimum': string;
}

type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerApplicationFrequencyEnum = 'FQAT' | 'FQDY' | 'FQHY' | 'FQMY' | 'FQOT' | 'FQQY' | 'FQSD' | 'FQWY' | 'FQYY'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerBankInterestRateTypeEnum = 'INBB' | 'INFR' | 'INGR' | 'INLR' | 'INNE' | 'INOT'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerCalculationFrequencyEnum = 'FQAT' | 'FQDY' | 'FQHY' | 'FQMY' | 'FQOT' | 'FQQY' | 'FQSD' | 'FQWY' | 'FQYY'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerDepositInterestAppliedCoverageEnum = 'INBA' | 'INTI' | 'INWH'


