/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Set of elements used to provide details of a generic number value related to the statement resource.
 * @export
 * @interface OBStatement2StatementValueInner
 */
export interface OBStatement2StatementValueInner {
    /**
     * Statement value type, in a coded form.
     * @type {string}
     * @memberof OBStatement2StatementValueInner
     */
    'Type': string;
    /**
     * Value associated with the statement value type.
     * @type {string}
     * @memberof OBStatement2StatementValueInner
     */
    'Value': string;
}

