/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount7 } from './obactive-or-historic-currency-and-amount7';
import { OBCreditDebitCode0 } from './obcredit-debit-code0';

/**
 * Set of elements used to provide details of a generic interest amount related to the statement resource.
 * @export
 * @interface OBStatement2StatementInterestInner
 */
export interface OBStatement2StatementInterestInner {
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount7}
     * @memberof OBStatement2StatementInterestInner
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount7;
    /**
     * Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount.
     * @type {OBCreditDebitCode0}
     * @memberof OBStatement2StatementInterestInner
     */
    'CreditDebitIndicator': OBCreditDebitCode0;
    /**
     * Description that may be available for the statement interest.
     * @type {string}
     * @memberof OBStatement2StatementInterestInner
     */
    'Description'?: string;
    /**
     * Specifies the statement fee type requested
     * @type {string}
     * @memberof OBStatement2StatementInterestInner
     */
    'Frequency'?: string;
    /**
     * field representing a percentage (e.g. 0.05 represents 5% and 0.9525 represents 95.25%). Note the number of decimal places may vary.
     * @type {number}
     * @memberof OBStatement2StatementInterestInner
     */
    'Rate'?: number;
    /**
     * Description that may be available for the statement Interest rate type.
     * @type {string}
     * @memberof OBStatement2StatementInterestInner
     */
    'RateType'?: string;
    /**
     * Interest amount type, in a coded form.
     * @type {string}
     * @memberof OBStatement2StatementInterestInner
     */
    'Type': string;
}

