/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount5 } from './obactive-or-historic-currency-and-amount5';

/**
 * Set of elements used to provide details of a benefit or reward amount for the statement resource.
 * @export
 * @interface OBStatement2StatementBenefitInner
 */
export interface OBStatement2StatementBenefitInner {
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount5}
     * @memberof OBStatement2StatementBenefitInner
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount5;
    /**
     * Benefit type, in a coded form.
     * @type {string}
     * @memberof OBStatement2StatementBenefitInner
     */
    'Type': string;
}

