/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount11 } from './obactive-or-historic-currency-and-amount11';
import { OBActiveOrHistoricCurrencyAndAmount2 } from './obactive-or-historic-currency-and-amount2';
import { OBActiveOrHistoricCurrencyAndAmount3 } from './obactive-or-historic-currency-and-amount3';
import { OBActiveOrHistoricCurrencyAndAmount4 } from './obactive-or-historic-currency-and-amount4';
import { OBBranchAndFinancialInstitutionIdentification51 } from './obbranch-and-financial-institution-identification51';
import { OBCashAccount51 } from './obcash-account51';
import { OBExternalStandingOrderStatus1Code } from './obexternal-standing-order-status1-code';

/**
 * 
 * @export
 * @interface OBStandingOrder6
 */
export interface OBStandingOrder6 {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'AccountId': string;
    /**
     * 
     * @type {OBCashAccount51}
     * @memberof OBStandingOrder6
     */
    'CreditorAccount'?: OBCashAccount51;
    /**
     * 
     * @type {OBBranchAndFinancialInstitutionIdentification51}
     * @memberof OBStandingOrder6
     */
    'CreditorAgent'?: OBBranchAndFinancialInstitutionIdentification51;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount4}
     * @memberof OBStandingOrder6
     */
    'FinalPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount4;
    /**
     * The date on which the final payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'FinalPaymentDateTime'?: string;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount2}
     * @memberof OBStandingOrder6
     */
    'FirstPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount2;
    /**
     * The date on which the first payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'FirstPaymentDateTime'?: string;
    /**
     * Individual Definitions: NotKnown - Not Known EvryDay - Every day EvryWorkgDay - Every working day IntrvlDay - An interval specified in number of calendar days (02 to 31) IntrvlWkDay - An interval specified in weeks (01 to 09), and the day within the week (01 to 07) WkInMnthDay - A monthly interval, specifying the week of the month (01 to 05) and day within the week (01 to 07) IntrvlMnthDay - An interval specified in months (between 01 to 06, 12, 24), specifying the day within the month (-05 to -01, 01 to 31) QtrDay - Quarterly (either ENGLISH, SCOTTISH, or RECEIVED) ENGLISH = Paid on the 25th March, 24th June, 29th September and 25th December. SCOTTISH = Paid on the 2nd February, 15th May, 1st August and 11th November. RECEIVED = Paid on the 20th March, 19th June, 24th September and 20th December. Individual Patterns: NotKnown (ScheduleCode) EvryDay (ScheduleCode) EvryWorkgDay (ScheduleCode) IntrvlDay:NoOfDay (ScheduleCode + NoOfDay) IntrvlWkDay:IntervalInWeeks:DayInWeek (ScheduleCode + IntervalInWeeks + DayInWeek) WkInMnthDay:WeekInMonth:DayInWeek (ScheduleCode + WeekInMonth + DayInWeek) IntrvlMnthDay:IntervalInMonths:DayInMonth (ScheduleCode + IntervalInMonths + DayInMonth) QtrDay: + either (ENGLISH, SCOTTISH or RECEIVED) ScheduleCode + QuarterDay The regular expression for this element combines five smaller versions for each permitted pattern. To aid legibility - the components are presented individually here: NotKnown EvryDay EvryWorkgDay IntrvlDay:((0[2-9])|([1-2][0-9])|3[0-1]) IntrvlWkDay:0[1-9]:0[1-7] WkInMnthDay:0[1-5]:0[1-7] IntrvlMnthDay:(0[1-6]|12|24):(-0[1-5]|0[1-9]|[12][0-9]|3[01]) QtrDay:(ENGLISH|SCOTTISH|RECEIVED) Full Regular Expression: ^(NotKnown)$|^(EvryDay)$|^(EvryWorkgDay)$|^(IntrvlDay:((0[2-9])|([1-2][0-9])|3[0-1]))$|^(IntrvlWkDay:0[1-9]:0[1-7])$|^(WkInMnthDay:0[1-5]:0[1-7])$|^(IntrvlMnthDay:(0[1-6]|12|24):(-0[1-5]|0[1-9]|[12][0-9]|3[01]))$|^(QtrDay:(ENGLISH|SCOTTISH|RECEIVED))$
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'Frequency': string;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount11}
     * @memberof OBStandingOrder6
     */
    'LastPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount11;
    /**
     * The date on which the last (most recent) payment for a Standing Order schedule was made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'LastPaymentDateTime'?: string;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount3}
     * @memberof OBStandingOrder6
     */
    'NextPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount3;
    /**
     * The date on which the next payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'NextPaymentDateTime'?: string;
    /**
     * Number of the payments that will be made in completing this frequency sequence including any executed since the sequence start date.
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'NumberOfPayments'?: string;
    /**
     * Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction. Usage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money. If the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor\'s reference or payment remittance identification should be quoted in the end-to-end transaction identification.
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'Reference'?: string;
    /**
     * A unique and immutable identifier used to identify the standing order resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBStandingOrder6
     */
    'StandingOrderId'?: string;
    /**
     * Specifies the status of the standing order in code form.
     * @type {OBExternalStandingOrderStatus1Code}
     * @memberof OBStandingOrder6
     */
    'StandingOrderStatusCode'?: OBExternalStandingOrderStatus1Code;
    /**
     * Additional information that can not be captured in the structured fields and/or any other specific block.
     * @type {{ [key: string]: any; }}
     * @memberof OBStandingOrder6
     */
    'SupplementaryData'?: { [key: string]: any; };
}

