/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBExternalStatementType1Code } from './obexternal-statement-type1-code';
import { OBStatement2StatementAmountInner } from './obstatement2-statement-amount-inner';
import { OBStatement2StatementBenefitInner } from './obstatement2-statement-benefit-inner';
import { OBStatement2StatementDateTimeInner } from './obstatement2-statement-date-time-inner';
import { OBStatement2StatementFeeInner } from './obstatement2-statement-fee-inner';
import { OBStatement2StatementInterestInner } from './obstatement2-statement-interest-inner';
import { OBStatement2StatementRateInner } from './obstatement2-statement-rate-inner';
import { OBStatement2StatementValueInner } from './obstatement2-statement-value-inner';

/**
 * Provides further details on a statement resource.
 * @export
 * @interface OBStatement2
 */
export interface OBStatement2 {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBStatement2
     */
    'AccountId': string;
    /**
     * Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2
     */
    'CreationDateTime': string;
    /**
     * Date and time at which the statement period ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2
     */
    'EndDateTime': string;
    /**
     * Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2
     */
    'StartDateTime': string;
    /**
     * 
     * @type {Array<OBStatement2StatementAmountInner>}
     * @memberof OBStatement2
     */
    'StatementAmount'?: Array<OBStatement2StatementAmountInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementBenefitInner>}
     * @memberof OBStatement2
     */
    'StatementBenefit'?: Array<OBStatement2StatementBenefitInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementDateTimeInner>}
     * @memberof OBStatement2
     */
    'StatementDateTime'?: Array<OBStatement2StatementDateTimeInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBStatement2
     */
    'StatementDescription'?: Array<string>;
    /**
     * 
     * @type {Array<OBStatement2StatementFeeInner>}
     * @memberof OBStatement2
     */
    'StatementFee'?: Array<OBStatement2StatementFeeInner>;
    /**
     * Unique identifier for the statement resource within an servicing institution. This identifier is both unique and immutable.
     * @type {string}
     * @memberof OBStatement2
     */
    'StatementId'?: string;
    /**
     * 
     * @type {Array<OBStatement2StatementInterestInner>}
     * @memberof OBStatement2
     */
    'StatementInterest'?: Array<OBStatement2StatementInterestInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementRateInner>}
     * @memberof OBStatement2
     */
    'StatementRate'?: Array<OBStatement2StatementRateInner>;
    /**
     * Unique reference for the statement. This reference may be optionally populated if available.
     * @type {string}
     * @memberof OBStatement2
     */
    'StatementReference'?: string;
    /**
     * 
     * @type {Array<OBStatement2StatementValueInner>}
     * @memberof OBStatement2
     */
    'StatementValue'?: Array<OBStatement2StatementValueInner>;
    /**
     * Statement type, in a coded form.
     * @type {OBExternalStatementType1Code}
     * @memberof OBStatement2
     */
    'Type': OBExternalStatementType1Code;
}

