/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Set of elements to describe the card instrument used in the transaction.
 * @export
 * @interface OBTransactionCardInstrument1
 */
export interface OBTransactionCardInstrument1 {
    /**
     * The card authorisation type.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'AuthorisationType'?: OBTransactionCardInstrument1AuthorisationTypeEnum;
    /**
     * Name of the card scheme.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'CardSchemeName': OBTransactionCardInstrument1CardSchemeNameEnum;
    /**
     * Identification assigned by an institution to identify the card instrument used in the transaction. This identification is known by the account owner, and may be masked.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'Identification'?: string;
    /**
     * Name of the cardholder using the card instrument.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'Name'?: string;
}

type OBTransactionCardInstrument1AuthorisationTypeEnum = 'ConsumerDevice' | 'Contactless' | 'None' | 'PIN'
type OBTransactionCardInstrument1CardSchemeNameEnum = 'AmericanExpress' | 'Diners' | 'Discover' | 'MasterCard' | 'VISA'


