/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount10 } from './obactive-or-historic-currency-and-amount10';
import { OBActiveOrHistoricCurrencyAndAmount9 } from './obactive-or-historic-currency-and-amount9';
import { OBBankTransactionCodeStructure1 } from './obbank-transaction-code-structure1';
import { OBBranchAndFinancialInstitutionIdentification61 } from './obbranch-and-financial-institution-identification61';
import { OBBranchAndFinancialInstitutionIdentification62 } from './obbranch-and-financial-institution-identification62';
import { OBCashAccount60 } from './obcash-account60';
import { OBCashAccount61 } from './obcash-account61';
import { OBCreditDebitCode1 } from './obcredit-debit-code1';
import { OBCurrencyExchange5 } from './obcurrency-exchange5';
import { OBEntryStatus1Code } from './obentry-status1-code';
import { OBMerchantDetails1 } from './obmerchant-details1';
import { OBTransactionCardInstrument1 } from './obtransaction-card-instrument1';
import { OBTransactionCashBalance } from './obtransaction-cash-balance';
import { OBTransactionMutability1Code } from './obtransaction-mutability1-code';
import { ProprietaryBankTransactionCodeStructure1 } from './proprietary-bank-transaction-code-structure1';

/**
 * Provides further details on an entry in the report.
 * @export
 * @interface OBTransaction6
 */
export interface OBTransaction6 {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBTransaction6
     */
    'AccountId': string;
    /**
     * Information that locates and identifies a specific address for a transaction entry, that is presented in free format text.
     * @type {string}
     * @memberof OBTransaction6
     */
    'AddressLine'?: string;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount9}
     * @memberof OBTransaction6
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount9;
    /**
     * 
     * @type {OBTransactionCashBalance}
     * @memberof OBTransaction6
     */
    'Balance'?: OBTransactionCashBalance;
    /**
     * 
     * @type {OBBankTransactionCodeStructure1}
     * @memberof OBTransaction6
     */
    'BankTransactionCode'?: OBBankTransactionCodeStructure1;
    /**
     * Date and time when a transaction entry is posted to an account on the account servicer\'s books. Usage: Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBTransaction6
     */
    'BookingDateTime': string;
    /**
     * 
     * @type {OBTransactionCardInstrument1}
     * @memberof OBTransaction6
     */
    'CardInstrument'?: OBTransactionCardInstrument1;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount10}
     * @memberof OBTransaction6
     */
    'ChargeAmount'?: OBActiveOrHistoricCurrencyAndAmount10;
    /**
     * Indicates whether the transaction is a credit or a debit entry.
     * @type {OBCreditDebitCode1}
     * @memberof OBTransaction6
     */
    'CreditDebitIndicator': OBCreditDebitCode1;
    /**
     * 
     * @type {OBCashAccount60}
     * @memberof OBTransaction6
     */
    'CreditorAccount'?: OBCashAccount60;
    /**
     * 
     * @type {OBBranchAndFinancialInstitutionIdentification61}
     * @memberof OBTransaction6
     */
    'CreditorAgent'?: OBBranchAndFinancialInstitutionIdentification61;
    /**
     * 
     * @type {OBCurrencyExchange5}
     * @memberof OBTransaction6
     */
    'CurrencyExchange'?: OBCurrencyExchange5;
    /**
     * 
     * @type {OBCashAccount61}
     * @memberof OBTransaction6
     */
    'DebtorAccount'?: OBCashAccount61;
    /**
     * 
     * @type {OBBranchAndFinancialInstitutionIdentification62}
     * @memberof OBTransaction6
     */
    'DebtorAgent'?: OBBranchAndFinancialInstitutionIdentification62;
    /**
     * 
     * @type {OBMerchantDetails1}
     * @memberof OBTransaction6
     */
    'MerchantDetails'?: OBMerchantDetails1;
    /**
     * 
     * @type {ProprietaryBankTransactionCodeStructure1}
     * @memberof OBTransaction6
     */
    'ProprietaryBankTransactionCode'?: ProprietaryBankTransactionCodeStructure1;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBTransaction6
     */
    'StatementReference'?: Array<string>;
    /**
     * Status of a transaction entry on the books of the account servicer.
     * @type {OBEntryStatus1Code}
     * @memberof OBTransaction6
     */
    'Status': OBEntryStatus1Code;
    /**
     * Additional information that can not be captured in the structured fields and/or any other specific block.
     * @type {{ [key: string]: any; }}
     * @memberof OBTransaction6
     */
    'SupplementaryData'?: { [key: string]: any; };
    /**
     * Unique identifier for the transaction within an servicing institution. This identifier is both unique and immutable.
     * @type {string}
     * @memberof OBTransaction6
     */
    'TransactionId'?: string;
    /**
     * Further details of the transaction.  This is the transaction narrative, which is unstructured text.
     * @type {string}
     * @memberof OBTransaction6
     */
    'TransactionInformation'?: string;
    /**
     * Specifies the Mutability of the Transaction record.
     * @type {OBTransactionMutability1Code}
     * @memberof OBTransaction6
     */
    'TransactionMutability'?: OBTransactionMutability1Code;
    /**
     * Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context.
     * @type {string}
     * @memberof OBTransaction6
     */
    'TransactionReference'?: string;
    /**
     * Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit transaction entry. Usage: If transaction entry status is pending and value date is present, then the value date refers to an expected/requested value date. For transaction entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the number of availability days.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBTransaction6
     */
    'ValueDateTime'?: string;
}

