/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Other Fee/charge type which is not available in the standard code set
 * @export
 * @interface OtherFeeTypeProperty
 */
export interface OtherFeeTypeProperty {
    /**
     * The four letter Mnemonic used within an XML file to identify a code
     * @type {string}
     * @memberof OtherFeeTypeProperty
     */
    'Code'?: string;
    /**
     * Description to describe the purpose of the code
     * @type {string}
     * @memberof OtherFeeTypeProperty
     */
    'Description': string;
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {string}
     * @memberof OtherFeeTypeProperty
     */
    'FeeCategory': OtherFeeTypePropertyFeeCategoryEnum;
    /**
     * Long name associated with the code
     * @type {string}
     * @memberof OtherFeeTypeProperty
     */
    'Name': string;
}

type OtherFeeTypePropertyFeeCategoryEnum = 'Other' | 'Servicing'


