/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeChargeCapPropertyInner1 } from './fee-charge-cap-property-inner1';
import { FeeChargeDetailPropertyInner1 } from './fee-charge-detail-property-inner1';

/**
 * Contains details of fees and charges which are not associated with either borrowing or features/benefits
 * @export
 * @interface OtherFeesChargesProperty
 */
export interface OtherFeesChargesProperty {
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     * @type {Array<FeeChargeCapPropertyInner1>}
     * @memberof OtherFeesChargesProperty
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner1>;
    /**
     * Other fees/charges details
     * @type {Array<FeeChargeDetailPropertyInner1>}
     * @memberof OtherFeesChargesProperty
     */
    'FeeChargeDetail': Array<FeeChargeDetailPropertyInner1>;
}

