/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeChargeCapPropertyInner } from './fee-charge-cap-property-inner';
import { FeeChargeDetailPropertyInner } from './fee-charge-detail-property-inner';
import { OtherTariffTypeProperty } from './other-tariff-type-property';

/**
 * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
 * @export
 * @interface OtherFeesChargesPropertyInner
 */
export interface OtherFeesChargesPropertyInner {
    /**
     * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
     * @type {Array<FeeChargeCapPropertyInner>}
     * @memberof OtherFeesChargesPropertyInner
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner>;
    /**
     * Other fees/charges details
     * @type {Array<FeeChargeDetailPropertyInner>}
     * @memberof OtherFeesChargesPropertyInner
     */
    'FeeChargeDetail': Array<FeeChargeDetailPropertyInner>;
    /**
     * 
     * @type {OtherTariffTypeProperty}
     * @memberof OtherFeesChargesPropertyInner
     */
    'OtherTariffType'?: OtherTariffTypeProperty;
    /**
     * Name of the tariff
     * @type {string}
     * @memberof OtherFeesChargesPropertyInner
     */
    'TariffName'?: string;
    /**
     * TariffType which defines the fee and charges.
     * @type {string}
     * @memberof OtherFeesChargesPropertyInner
     */
    'TariffType'?: OtherFeesChargesPropertyInnerTariffTypeEnum;
}

type OtherFeesChargesPropertyInnerTariffTypeEnum = 'Electronic' | 'Mixed' | 'Other'


