/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherFeeTypePropertyInner } from './other-fee-type-property-inner';

/**
 * Details about any caps (maximum charges) that apply to a particular fee/charge
 * @export
 * @interface OverdraftFeeChargeCapPropertyInner1
 */
export interface OverdraftFeeChargeCapPropertyInner1 {
    /**
     * Period e.g. day, week, month etc. for which the fee/charge is capped
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'CappingPeriod'?: OverdraftFeeChargeCapPropertyInner1CappingPeriodEnum;
    /**
     * Cap amount charged for a fee/charge
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'FeeCapAmount'?: string;
    /**
     * fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount
     * @type {number}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'FeeCapOccurrence'?: number;
    /**
     * Fee/charge type which is being capped
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'FeeType': Array<OverdraftFeeChargeCapPropertyInner1FeeTypeEnum>;
    /**
     * Indicates that this is the minimum/ maximum fee/charge that can be applied by the financial institution
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'MinMaxType': OverdraftFeeChargeCapPropertyInner1MinMaxTypeEnum;
    /**
     * Notes related to Overdraft fee charge cap
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * Other fee type code which is not available in the standard code set
     * @type {Array<OtherFeeTypePropertyInner>}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'OtherFeeType'?: Array<OtherFeeTypePropertyInner>;
    /**
     * Specifies for the overdraft control feature/benefit
     * @type {boolean}
     * @memberof OverdraftFeeChargeCapPropertyInner1
     */
    'OverdraftControlIndicator'?: boolean;
}

type OverdraftFeeChargeCapPropertyInner1CappingPeriodEnum = 'AcademicTerm' | 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year'
type OverdraftFeeChargeCapPropertyInner1FeeTypeEnum = 'ArrangedOverdraft' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'AnnualReview' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeCapPropertyInner1MinMaxTypeEnum = 'Minimum' | 'Maximum'


