/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeesChargesPropertyInner3 } from './overdraft-fees-charges-property-inner3';

/**
 * Provides overdraft details for a specific tier or band
 * @export
 * @interface OverdraftTierBandPropertyInner1
 */
export interface OverdraftTierBandPropertyInner1 {
    /**
     * Indicates that a bank provides the overdraft limit up to TierValueMIn to all customers automatically
     * @type {boolean}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'BankGuaranteedIndicator'?: boolean;
    /**
     * EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'EAR'?: string;
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'Identification'?: string;
    /**
     * Optional additional notes to supplement the Tier/band details
     * @type {Array<string>}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * Overdraft fees and charges
     * @type {Array<OverdraftFeesChargesPropertyInner3>}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'OverdraftFeesCharges'?: Array<OverdraftFeesChargesPropertyInner3>;
    /**
     * Interest charged on whole amount or tiered/banded
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'OverdraftInterestChargingCoverage'?: OverdraftTierBandPropertyInner1OverdraftInterestChargingCoverageEnum;
    /**
     * An annual percentage rate (APR) is the annual rate charged for borrowing or earned through an investment. APR is expressed as a percentage that represents the actual yearly cost of funds over the term of a loan. This includes any fees or additional costs associated with the transaction but does not take compounding into account.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'RepresentativeAPR'?: string;
    /**
     * Maximum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'TierValueMax'?: string;
    /**
     * Minimum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'TierValueMin': string;
}

type OverdraftTierBandPropertyInner1OverdraftInterestChargingCoverageEnum = 'Tiered' | 'Whole'


