/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherFeeTypePropertyInner } from './other-fee-type-property-inner';

/**
 * Details about any caps (maximum charges) that apply to a particular fee/charge. Capping can either be based on an amount (in gbp), an amount (in items) or a rate.
 * @export
 * @interface OverdraftFeeChargeCapPropertyInner
 */
export interface OverdraftFeeChargeCapPropertyInner {
    /**
     * Period e.g. day, week, month etc. for which the fee/charge is capped
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'CappingPeriod'?: OverdraftFeeChargeCapPropertyInnerCappingPeriodEnum;
    /**
     * Cap amount charged for a fee/charge
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'FeeCapAmount'?: string;
    /**
     * Indicates whether the advertised overdraft rate is guaranteed to be offered to a borrower by the bank e.g. if it’s part of a government scheme, or whether the rate may vary dependent on the applicant’s circumstances.
     * @type {number}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'FeeCapOccurrence'?: number;
    /**
     * Fee/charge type which is being capped
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'FeeType': Array<OverdraftFeeChargeCapPropertyInnerFeeTypeEnum>;
    /**
     * Min Max type
     * @type {string}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'MinMaxType': OverdraftFeeChargeCapPropertyInnerMinMaxTypeEnum;
    /**
     * Notes related to Overdraft fee charge cap
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Other fee type code which is not available in the standard code set
     * @type {Array<OtherFeeTypePropertyInner>}
     * @memberof OverdraftFeeChargeCapPropertyInner
     */
    'OtherFeeType'?: Array<OtherFeeTypePropertyInner>;
}

type OverdraftFeeChargeCapPropertyInnerCappingPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year'
type OverdraftFeeChargeCapPropertyInnerFeeTypeEnum = 'ArrangedOverdraft' | 'AnnualReview' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeCapPropertyInnerMinMaxTypeEnum = 'Minimum' | 'Maximum'


