/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftTierBandSetPropertyInner } from './overdraft-tier-band-set-property-inner';

/**
 * Borrowing details
 * @export
 * @interface OverdraftProperty
 */
export interface OverdraftProperty {
    /**
     * Associated Notes about the overdraft rates
     * @type {Array<string>}
     * @memberof OverdraftProperty
     */
    'Notes'?: Array<string>;
    /**
     * Tier band set details
     * @type {Array<OverdraftTierBandSetPropertyInner>}
     * @memberof OverdraftProperty
     */
    'OverdraftTierBandSet': Array<OverdraftTierBandSetPropertyInner>;
}

