/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeeChargeCapPropertyInner } from './overdraft-fee-charge-cap-property-inner';
import { OverdraftFeeChargeDetailPropertyInner } from './overdraft-fee-charge-detail-property-inner';

/**
 * Overdraft fees and charges
 * @export
 * @interface OverdraftFeesChargesPropertyInner1
 */
export interface OverdraftFeesChargesPropertyInner1 {
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge. Capping can either be based on an amount (in gbp), an amount (in items) or a rate.
     * @type {Array<OverdraftFeeChargeCapPropertyInner>}
     * @memberof OverdraftFeesChargesPropertyInner1
     */
    'OverdraftFeeChargeCap'?: Array<OverdraftFeeChargeCapPropertyInner>;
    /**
     * Details about the fees/charges
     * @type {Array<OverdraftFeeChargeDetailPropertyInner>}
     * @memberof OverdraftFeesChargesPropertyInner1
     */
    'OverdraftFeeChargeDetail': Array<OverdraftFeeChargeDetailPropertyInner>;
}

