/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeeChargeCapPropertyInner1 } from './overdraft-fee-charge-cap-property-inner1';
import { OverdraftFeeChargeDetailPropertyInner1 } from './overdraft-fee-charge-detail-property-inner1';

/**
 * Overdraft fees and charges
 * @export
 * @interface OverdraftFeesChargesPropertyInner3
 */
export interface OverdraftFeesChargesPropertyInner3 {
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     * @type {Array<OverdraftFeeChargeCapPropertyInner1>}
     * @memberof OverdraftFeesChargesPropertyInner3
     */
    'OverdraftFeeChargeCap'?: Array<OverdraftFeeChargeCapPropertyInner1>;
    /**
     * Details about the fees/charges
     * @type {Array<OverdraftFeeChargeDetailPropertyInner1>}
     * @memberof OverdraftFeesChargesPropertyInner3
     */
    'OverdraftFeeChargeDetail': Array<OverdraftFeeChargeDetailPropertyInner1>;
}

