/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeesChargesPropertyInner } from './overdraft-fees-charges-property-inner';
import { OverdraftTierBandPropertyInner } from './overdraft-tier-band-property-inner';

/**
 * Tier band set details
 * @export
 * @interface OverdraftTierBandSetPropertyInner
 */
export interface OverdraftTierBandSetPropertyInner {
    /**
     * Indicates if the Overdraft is authorised (Y) or unauthorised (N)
     * @type {boolean}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'AuthorisedIndicator'?: boolean;
    /**
     * When a customer exceeds their credit limit, a financial institution will not charge the customer unauthorised overdraft charges if they do not exceed by more than the buffer amount. Note: Authorised overdraft charges may still apply.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'BufferAmount'?: string;
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft product.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'Identification'?: string;
    /**
     * Optional additional notes to supplement the overdraft Tier Band Set details
     * @type {Array<string>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Overdraft fees and charges details
     * @type {Array<OverdraftFeesChargesPropertyInner>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftFeesCharges'?: Array<OverdraftFeesChargesPropertyInner>;
    /**
     * Provides overdraft details for a specific tier or band
     * @type {Array<OverdraftTierBandPropertyInner>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftTierBand': Array<OverdraftTierBandPropertyInner>;
    /**
     * An overdraft can either be \'committed\' which means that the facility cannot be withdrawn without reasonable notification before it\'s agreed end date, or \'on demand\' which means that the financial institution can demand repayment at any point in time.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftType'?: OverdraftTierBandSetPropertyInnerOverdraftTypeEnum;
    /**
     * The methodology of how overdraft is charged. It can be: \'Whole\'  Where the same charge/rate is applied to the entirety of the overdraft balance (where charges are applicable).  \'Tiered\' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount tiers defined by the lending financial organisation \'Banded\' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount bands defined by a government organisation.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'TierBandMethod': OverdraftTierBandSetPropertyInnerTierBandMethodEnum;
}

type OverdraftTierBandSetPropertyInnerOverdraftTypeEnum = 'Committed' | 'OnDemand'
type OverdraftTierBandSetPropertyInnerTierBandMethodEnum = 'Banded' | 'Tiered' | 'Whole'


