/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty } from './other-application-frequency-property';
import { OtherCalculationFrequencyProperty } from './other-calculation-frequency-property';
import { OtherFeeRateTypeProperty1 } from './other-fee-rate-type-property1';
import { OtherFeeTypeProperty1 } from './other-fee-type-property1';
import { OverdraftFeeChargeCapProperty } from './overdraft-fee-charge-cap-property';

/**
 * Details about the fees/charges
 * @export
 * @interface OverdraftFeeChargeDetailPropertyInner1
 */
export interface OverdraftFeeChargeDetailPropertyInner1 {
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'ApplicationFrequency': OverdraftFeeChargeDetailPropertyInner1ApplicationFrequencyEnum;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'CalculationFrequency'?: OverdraftFeeChargeDetailPropertyInner1CalculationFrequencyEnum;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeRateType'?: OverdraftFeeChargeDetailPropertyInner1FeeRateTypeEnum;
    /**
     * Overdraft fee type
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeType': OverdraftFeeChargeDetailPropertyInner1FeeTypeEnum;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Free text for capturing any other info related to Overdraft Fees Charge Details
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty;
    /**
     * 
     * @type {OtherFeeRateTypeProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty1;
    /**
     * 
     * @type {OtherFeeTypeProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherFeeType'?: OtherFeeTypeProperty1;
    /**
     * Specifies for the overdraft control feature/benefit
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * 
     * @type {OverdraftFeeChargeCapProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OverdraftFeeChargeCap'?: OverdraftFeeChargeCapProperty;
}

type OverdraftFeeChargeDetailPropertyInner1ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInner1CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInner1FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'
type OverdraftFeeChargeDetailPropertyInner1FeeTypeEnum = 'ArrangedOverdraft' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'AnnualReview' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'


