/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeesChargesPropertyInner1 } from './overdraft-fees-charges-property-inner1';

/**
 * Provides overdraft details for a specific tier or band
 * @export
 * @interface OverdraftTierBandPropertyInner
 */
export interface OverdraftTierBandPropertyInner {
    /**
     * Specifies the maximum length of a band for a fixed overdraft agreement
     * @type {number}
     * @memberof OverdraftTierBandPropertyInner
     */
    'AgreementLengthMax'?: number;
    /**
     * Specifies the minimum length of a band for a fixed overdraft agreement
     * @type {number}
     * @memberof OverdraftTierBandPropertyInner
     */
    'AgreementLengthMin'?: number;
    /**
     * Specifies the period of a fixed length overdraft agreement
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'AgreementPeriod'?: OverdraftTierBandPropertyInnerAgreementPeriodEnum;
    /**
     * Indicates whether the advertised overdraft rate is guaranteed to be offered to a borrower by the bank e.g. if it’s part of a government scheme, or whether the rate may vary dependent on the applicant’s circumstances.
     * @type {boolean}
     * @memberof OverdraftTierBandPropertyInner
     */
    'BankGuaranteedIndicator'?: boolean;
    /**
     * EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'EAR'?: string;
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'Identification'?: string;
    /**
     * Optional additional notes to supplement the Tier/band details
     * @type {Array<string>}
     * @memberof OverdraftTierBandPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Overdraft fees and charges
     * @type {Array<OverdraftFeesChargesPropertyInner1>}
     * @memberof OverdraftTierBandPropertyInner
     */
    'OverdraftFeesCharges'?: Array<OverdraftFeesChargesPropertyInner1>;
    /**
     * Refers to which interest rate is applied when interests are tiered. For example, if an overdraft balance is £2k and the interest tiers are:- 0-£500 0.1%, 500-1000 0.2%, 1000-10000 0.5%, then the applicable interest rate could either be 0.5% of the entire balance (since the account balance sits in the top interest tier) or (0.1%*500)+(0.2%*500)+(0.5%*1000). In the 1st situation, we say the interest is applied to the ‘Whole’ of the account balance,  and in the 2nd that it is ‘Tiered’.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'OverdraftInterestChargingCoverage'?: OverdraftTierBandPropertyInnerOverdraftInterestChargingCoverageEnum;
    /**
     * An annual percentage rate (APR) is the annual rate charged for borrowing or earned through an investment. APR is expressed as a percentage that represents the actual yearly cost of funds over the term of a loan. This includes any fees or additional costs associated with the transaction but does not take compounding into account.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'RepresentativeAPR'?: string;
    /**
     * Maximum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'TierValueMax'?: string;
    /**
     * Minimum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner
     */
    'TierValueMin': string;
}

type OverdraftTierBandPropertyInnerAgreementPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year'
type OverdraftTierBandPropertyInnerOverdraftInterestChargingCoverageEnum = 'Banded' | 'Tiered' | 'Whole'


