/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductDetailsProperty1
 */
export interface ProductDetailsProperty1 {
    /**
     * The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
     * @type {string}
     * @memberof ProductDetailsProperty1
     */
    'MonthlyMaximumCharge'?: string;
    /**
     * Optional additional notes to supplement the Core product details
     * @type {Array<string>}
     * @memberof ProductDetailsProperty1
     */
    'Notes'?: Array<string>;
    /**
     * Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to PCA products, they are segmented in relation to different markets that they wish to focus on. 
     * @type {Array<string>}
     * @memberof ProductDetailsProperty1
     */
    'Segment'?: Array<ProductDetailsProperty1SegmentEnum>;
}

type ProductDetailsProperty1SegmentEnum = 'Basic' | 'BenefitAndReward' | 'CreditInterest' | 'Cashback' | 'General' | 'Graduate' | 'Other' | 'Overdraft' | 'Packaged' | 'Premium' | 'Reward' | 'Student' | 'YoungAdult' | 'Youth'


