/*
Account and Transaction API Specification

Swagger for Account and Transaction API Specification

The version of the OpenAPI document: 3.1.7
Contact: ServiceDesk@openbanking.org.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty } from './other-application-frequency-property';
import { OtherBankInterestTypeProperty } from './other-bank-interest-type-property';
import { OtherCalculationFrequencyProperty } from './other-calculation-frequency-property';

/**
 * Tier Band Details
 * @export
 * @interface TierBandPropertyInner
 */
export interface TierBandPropertyInner {
    /**
     * The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.   Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'AER': string;
    /**
     * How often is interest applied to the BCA for this tier/band i.e. how often the financial institution pays accumulated interest to the customer\'s BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'ApplicationFrequency': TierBandPropertyInnerApplicationFrequencyEnum;
    /**
     * Bank Interest for the BCA product
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'BankInterestRate'?: string;
    /**
     * Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'BankInterestRateType'?: TierBandPropertyInnerBankInterestRateTypeEnum;
    /**
     * How often is credit interest calculated for the account.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'CalculationFrequency'?: TierBandPropertyInnerCalculationFrequencyEnum;
    /**
     * Amount on which Interest applied.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'DepositInterestAppliedCoverage'?: TierBandPropertyInnerDepositInterestAppliedCoverageEnum;
    /**
     * Type of interest rate, Fixed or Variable
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'FixedVariableInterestRateType': TierBandPropertyInnerFixedVariableInterestRateTypeEnum;
    /**
     * Unique and unambiguous identification of a  Tier Band for a BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'Identification'?: string;
    /**
     * Optional additional notes to supplement the Tier Band details
     * @type {Array<string>}
     * @memberof TierBandPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty;
    /**
     * 
     * @type {OtherBankInterestTypeProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherBankInterestType'?: OtherBankInterestTypeProperty;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty;
    /**
     * Maximum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'TierValueMaximum'?: string;
    /**
     * Minimum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'TierValueMinimum': string;
}

type TierBandPropertyInnerApplicationFrequencyEnum = 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInnerBankInterestRateTypeEnum = 'Gross' | 'Other'
type TierBandPropertyInnerCalculationFrequencyEnum = 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInnerDepositInterestAppliedCoverageEnum = 'Banded' | 'Tiered' | 'Whole'
type TierBandPropertyInnerFixedVariableInterestRateTypeEnum = 'Fixed' | 'Variable'


